version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    env_file: 
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

# app:
#   build: .
#   container_name: task-manager-backend
#   restart: always
#   env_file: 
#     - .env
#   depends_on:
#     - db
#   ports:
#     - "8080:8080"
 
#   volumes:
#     - .:/app

  
volumes:
  mysql_data:
    driver: local